name: publish-to-npm

on:
  push:
    branches:
      - master

jobs:
 build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
    - name: Upload Krane CLI binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/krane-linux
        asset_name: krane-cli
        tag: ${{ github.ref }}
    - run: npm i -g pkg
    - run: pkg .
      
