name: publish-to-npm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        include:  
          - os: ubuntu-latest
            artifact_name: krane-linux
            asset_name: krane-cli-linux
          - os: windows-latest
            artifact_name: krane-win.exe
            asset_name: krane-cli-windows
          - os: macos-latest
            artifact_name: krane-macos
            asset_name: krane-cli-macos

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build 
      run: npm i -g pkg && pkg . && ls -la
    
    - name: Upload Krane CLI binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
