name: publish-to-npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: krane-cli
            asset_name: krane-cli-linux
          - os: windows-latest
            artifact_name: krane-cli.exe
            asset_name: krane-cli-windows
          - os: macos-latest
            artifact_name: krane-cli
            asset_name: krane-cli-macos

    steps:
    - uses: actions/checkout@v2
    - name: Build
    - run: npm i -g pkg
    - run: pkg .
    
    - name: Upload Krane CLI binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
